### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by rugk** [ether/ep_disable_custom_scripts_and_styles#1]
On my main Etherpad page (no pad opened) I can still see these files being loaded:

```
200 /CustomSubDir/static/custom/index.css (0 KB)
200 /CustomSubDir/static/custom/index.js (0,18 KB)
```

The JS file is just the default one:

``` js
function customStart()
{
  //define your javascript here
  //jquery is available - except index.js
  //you can load extra scripts with $.getScript http://api.jquery.com/jQuery.getScript/
}
```

**Comment by JohnMcLear** [comment]
Is your minify set to false and maxAge 0?  Have you tried clearing your cache?

**Comment by rugk** [comment]
No it's set to yes and maxAge to the default number (`21600`). Why should I do so?

In my browser I of course made sure it does not use the cache (reloading via `Strg+Shift+F5`).

**Comment by JohnMcLear** [comment]
Please see the development documentation it explains this.

**Comment by rugk** [comment]
Of Etherpad? Because this plugin has no doc.
And the only doc about custom static files I could find is [this one](http://etherpad.org/doc/v1.6.0/#index_custom_static_files) and there is not mentioned that you need to change the cache values.

So why should I e.g. disable minify? I mean this plugin should only remove some unnecessary file loadings, so it should not matter in any way whether my JS files are minified.

Additionally your instructions are contradictory to the ones [listed here](https://github.com/ether/etherpad-lite/wiki/Optimizing-Etherpad). Because when I install this plugin I obviously want to optimize Etherpad. And so I'm of course not going to disable minify or disable the caching of my JS files.

BTW this also only happens on the main Etherpad page. (no pad opened)

**Comment by JohnMcLear** [comment]
maxage and minify need to be set WHILE developing then you to into production after and that's when you set them back to the normal values....  Docs are in Etherpads Github Wiki

**Comment by rugk** [comment]
Okay, so I am not developing. Just want to remove these file loadings. In a productive system of course...
So to come back to this issue: These files are still loaded.

**Comment by JohnMcLear** [comment]
You should have a go at developing, I think you would do a good job of it :)

**Comment by rugk** [comment]
So this does still not fix this issue...

**Comment by JohnMcLear** [comment]
You have the power in your hands :)

**Comment by JohnMcLear** [comment]
scripts and styles removed from top window but not inner editor, fwiw..

**Comment by JohnMcLear** [comment]
Fixed, you will nede to pull latest etherpad develop branch.  It was 1/2 working fwiw ;)

**Comment by rugk** [comment]
Thanks. It is now working! :tada:
